baseurl = "https://marinebon.github.io/mbon_org" 
title = "Marine Biodiversity Observation Network"
theme = "hugo-universal-theme"
themesDir = "themes"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# number of words of summarized post content (default 70)
summaryLength = 70

# not pluralize title pages by default
pluralizelisttitles = false

[services]
    # Enable comments by entering your Disqus shortname
    [services.disqus]
        shortname = ""  # empty disabled Disqus
    # Enable Google Analytics by entering your tracking code
    [services.googleAnalytics]
        id = ""

# Define the number of posts per page
[pagination]
    pagerSize = 10

# === Main menu
[menu] 
[[menu.main]]
    name       = "About Us"
    identifier = "menu.about"
    weight     = 1
    params.customPartial = "menu-about-us" 


[[menu.main]]
    name       = "The Network"
    identifier = "menu.network"
    url        = "/network"
    params.customPartial = "menu-network"
    weight     = 2

[[menu.main]]
    name       = "Data & Products"
    identifier = "menu.products"
    url        = "/products"
    weight     = 3

[[menu.main]]
    name       = "Media"
    identifier = "menu.media"
    url        = "/media"
    weight     = 4
    params.customPartial = "menu-media"

[[menu.main]]
    name       = "Contact"
    identifier = "menu.contact"
    url        = ""
    weight     = 5
    
# === Top bar social links menu
#[[menu.topbar]]
#    weight = 1
#    name = "Phone"
#    url = "tel:+12 34 567 89 01"
#    pre = "<i class='fas fa-2x fa-phone'></i>"

[[menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/marinebon"
    pre = "<i class='fab fa-2x fa-github'></i>"

#[[menu.topbar]]
#    weight = 3
#    name = "Facebook"
#    url = "https://facebook.com"
#    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 4
    name = "X"
    url = "https://x.com/MarineBON1"
    pre = "<i class='fab fa-2x fa-x-twitter'></i>"

#[[menu.topbar]]
#    weight = 5
#    name = "Email"
#    url = "mailto:hello@universal.com"
#    pre = "<i class='fas fa-2x fa-envelope'></i>"

[[menu.topbar]]
    weight = 3
    name = "youtube"
    url = "https://www.youtube.com/channel/UCiXkc3xHhl9bOHYdE3LtWMg"
    pre = "<i class='fab fa-2x fa-youtube'></i>"


[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = []
    mainSections = ["blog"]
    defaultDescription = "Blog Item..."

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = true
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 50 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - register your account to https://formspree.io/register
    # - login and create new form
    # - set your form's endpoint url under 'formspree_action' below
    # - upload the generated site to your server
    # - test a dummy email yourself
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io endpoint url
    formspree_action = "https://formspree.io/sample/of/endpoint"
    contact_form_ajax = false

    # Formspree form supports Google reCAPTCHA Key (type v2).
    # If you use this feature, you should enable reCAPTCHA feature in the Formspree dashboard.
    #
    # By default, Formspree use a redirect page for recaptcha widget.
    # If you use a recaptcha widget in your contact page, you should do next steps.
    # (if you don't want, skip these steps)
    #
    #   1. register your site on Google recaptcha admin page: https://www.google.com/recaptcha/admin
    #   2. select reCAPTCHA v2 and checkbox widget type.
    #   3. remember site key and secret key.
    #   4. enter secret key into "Custom reCAPTCHA Key" field in your Formspree form setting page.
    #   5. change `enableRecaptchaInContactForm` is to true
    #   6. enter site key into `googleRecaptchaKey` to enable a recaptcha widget in your page.
    #
    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>The Marine Biodiversity Observation Network (MBON) is a growing global initiative composed of regional networks of scientists, resource managers, and end-users working to integrate data from existing long-term programs to improve our understanding of changes and connections between marine biodiversity and ecosystem functions.</p>"

    copyright = '<a href="https://github.com/marinebon/mbon_org/issues">Report an issue with this website</a>'

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "MBON"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>Universal Ltd.</strong>
        <br>13/25 New Avenue
        <br>Newtown upon River
        <br>45Y 73J
        <br>England
        <br>
        <strong>Great Britain</strong>
      </p>
      """

[permalinks]
    blog = "/blog/:year/:month/:day/:slug/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="mailto:hello@universal.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 6
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 4
    auto_play = false
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'data/carousel_main_page'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.features]
    enable = true
    cols = 4 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.
    title = "MBON ECOSYSTEM"
    subtitle = "MBON is a growing global initiative composed of regional networks of scientists, resource managers, and end-users working to integrate data from existing long-term programs to improve our understanding of changes and connections between marine biodiversity and ecosystem functions."

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "Strategy and Implementation?"
    subtitle = "The MBON Strategic and Implementation Plan reflects the ocean observing community engagement to deliver a common vision, stronger statement, and steady partnership to achieve a sustained system of global ocean observations and data management."
    link_url = "#"
    link_text = "TODO..."

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
#    title = "Supporting Organizations"
#    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Latest News & Updates"
    subtitle = "Learn what we and our partners are doing around the globe."
    hide_summary = false

[params.footer.recent_posts]
    enable = true

[taxonomies]
    category = "categories"
    tag = "tags"
    author = "authors"
